language: "shell"
sudo: "true"
os: centos7x
branches:
  only:
    - master
script:
  - P=$(pwd)
  - curl https://sh.rustup.rs -o rustup.sh
  - chmod +x rustup.sh
  - ./rustup.sh --default-toolchain nightly -y
  - sudo yum update -y
  - sudo yum install -y centos-release-gluster openssl-devel.x86_64
  - sudo yum install -y glusterfs-api-devel glusterfs-api gcc rpm-build
  - ~/.cargo/bin/cargo build --release --all
  - sudo rpmbuild --define "_builddir ${P}" -bb gluster-flexvol.spec
  - ls /root/rpmbuild/RPMS/x86_64/
