[package]
name = "gluster-flexvol"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
clap = "*"
gfapi-sys  = "~0.3"
# jsonwebtoken = "~4"
log = "*"
rocket = "~0.3"
rocket_codegen = "~0.3"
rocket_contrib = "~0.3"
serde = "~1.0"
serde_derive = "~1.0"
# serde_json = "~1.0"
